"""Add specialization to Coach model

Revision ID: 0647cee55a14
Revises: 48ca8ba876c0
Create Date: 2025-08-27 10:15:38.395198

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0647cee55a14"
down_revision: Union[str, None] = "48ca8ba876c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "referees", sa.Column("nationality", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "referees", sa.Column("qualifications", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("referees", "qualifications")
    op.drop_column("referees", "nationality")
    # ### end Alembic commands ###
