"""Add specialization to Coach model

Revision ID: 48ca8ba876c0
Revises: 9067756d7394
Create Date: 2025-08-27 10:02:20.340467

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "48ca8ba876c0"
down_revision: Union[str, None] = "9067756d7394"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "coaches", sa.Column("nationality", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("coaches", "nationality")
    # ### end Alembic commands ###
