"""Add specialization to Coach model

Revision ID: 9067756d7394
Revises: c0bcb999f7cb
Create Date: 2025-08-27 09:59:36.274899

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9067756d7394"
down_revision: Union[str, None] = "c0bcb999f7cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "managers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("strategy", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.CheckConstraint("strategy IS NOT NULL", name="chk_manager_strategy"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_managers_id"), "managers", ["id"], unique=False)
    op.add_column(
        "coaches", sa.Column("specialization", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("coaches", "specialization")
    op.drop_index(op.f("ix_managers_id"), table_name="managers")
    op.drop_table("managers")
    # ### end Alembic commands ###
