"""Add specialization to Coach model

Revision ID: d46d8ccf0e6b
Revises: 0647cee55a14
Create Date: 2025-08-27 10:17:07.023767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd46d8ccf0e6b'
down_revision: Union[str, None] = '0647cee55a14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referees', sa.Column('qualification_level', sa.String(length=255), nullable=True))
    op.drop_column('referees', 'qualifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referees', sa.Column('qualifications', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('referees', 'qualification_level')
    # ### end Alembic commands ###

