name: Code Quality

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt
        pip install black isort mypy pylint
    
    - name: Format check with black
      run: |
        black --check --diff app/
    
    - name: Import sorting check with isort
      run: |
        isort --check-only --diff app/
    
    - name: Type checking with mypy
      run: |
        mypy app/ --ignore-missing-imports || true
    
    - name: Lint with pylint
      run: |
        pylint app/ --exit-zero --reports=yes --output-format=json > pylint-report.json || true
    
    - name: Upload code quality reports
      uses: actions/upload-artifact@v3
      with:
        name: code-quality-reports
        path: |
          pylint-report.json

  documentation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt
        pip install sphinx sphinx-rtd-theme
    
    - name: Check API documentation
      run: |
        python -c "
        from app.main import app
        import json
        from fastapi.openapi.utils import get_openapi
        
        openapi_schema = get_openapi(
            title=app.title,
            version=app.version,
            description=app.description,
            routes=app.routes,
        )
        
        with open('openapi.json', 'w') as f:
            json.dump(openapi_schema, f, indent=2)
        
        print('✅ API documentation generated successfully')
        "
    
    - name: Upload API documentation
      uses: actions/upload-artifact@v3
      with:
        name: api-documentation
        path: openapi.json
