name: Demo Environment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  demo-setup:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt
    
    - name: Initialize demo database
      run: |
        python seed_data.py
    
    - name: Start demo server
      run: |
        uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        sleep 5
        SERVER_PID=$!
        
        # Test demo endpoints
        curl -f http://localhost:8000/demo || exit 1
        curl -f http://localhost:8000/docs || exit 1
        curl -f http://localhost:8000/api/v1/teams/ || exit 1
        
        kill $SERVER_PID
        echo "✅ Demo environment tested successfully"
    
    - name: Generate demo report
      run: |
        echo "# Demo Environment Report" > demo-report.md
        echo "" >> demo-report.md
        echo "## Deployment Status: ✅ SUCCESS" >> demo-report.md
        echo "" >> demo-report.md
        echo "## Available Endpoints:" >> demo-report.md
        echo "- Demo Interface: /demo" >> demo-report.md
        echo "- API Documentation: /docs" >> demo-report.md
        echo "- Teams API: /api/v1/teams/" >> demo-report.md
        echo "- Players API: /api/v1/players/" >> demo-report.md
        echo "- Matches API: /api/v1/matches/" >> demo-report.md
        echo "" >> demo-report.md
        echo "## Database Status:" >> demo-report.md
        echo "- ✅ Seed data initialized" >> demo-report.md
        echo "- ✅ 8 Premier League teams" >> demo-report.md
        echo "- ✅ 20+ realistic players" >> demo-report.md
        echo "- ✅ Match fixtures available" >> demo-report.md
        echo "" >> demo-report.md
        echo "Generated on: $(date)" >> demo-report.md
    
    - name: Upload demo report
      uses: actions/upload-artifact@v4
      with:
        name: demo-environment-report
        path: demo-report.md
    
    - name: Comment on PR (if applicable)
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const report = fs.readFileSync('demo-report.md', 'utf8');
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## 🚀 Demo Environment Ready!\n\n${report}`
          });
