name: Dependency Updates

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools safety
    
    - name: Check for outdated packages
      run: |
        pip list --outdated --format=json > outdated-packages.json
        cat outdated-packages.json
    
    - name: Security vulnerability check
      run: |
        safety check --json --output safety-report.json || true
        cat safety-report.json
    
    - name: Upload dependency reports
      uses: actions/upload-artifact@v4
      with:
        name: dependency-reports
        path: |
          outdated-packages.json
          safety-report.json
    
    - name: Create issue for vulnerabilities
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Security vulnerabilities detected in dependencies',
            body: 'Automated security scan found vulnerabilities in project dependencies. Please check the workflow logs and update packages accordingly.',
            labels: ['security', 'dependencies']
          })
